upwork.api.client-id=
upwork.api.client-secret=

apify.token=

search.criteria.min-hourly-rate=35
search.criteria.min-fixed-price=100
search.criteria.category-ids=531770282580668418
search.criteria.locations=Europe,Asia
search.criteria.searchExpression=(Java OR Spring OR Angular)

spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=
spring.mail.to=
