upwork.api.client-id=
upwork.api.client-secret=

apify.token=

search.criteria.min-hourly-rate=35
search.criteria.min-fixed-price=100
search.criteria.category-ids=531770282580668418
search.criteria.locations=Europe,Asia
search.criteria.searchExpression=(Java OR Spring OR Angular)

notifications.email.enabled=false

spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=
spring.mail.to=

spring.datasource.url=jdbc:mysql://localhost:3306/upwork_alert
spring.datasource.username=
spring.datasource.password=
spring.datasource.hikari.data-source-properties.useUnicode=true
spring.datasource.hikari.data-source-properties.characterEncoding=utf8

spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.connection.Charset=utf8
spring.jpa.properties.hibernate.connection.characterEncoding=utf8
spring.jpa.properties.hibernate.connection.useUnicode=true

spring.flyway.schemas=upwork_alert
